import { Divider } from "@ui-kitten/components";
import { MDivider } from "../../baseUI/mDivider";
import MText from "../../baseUI/mText";
import MVStack from "../../baseUI/mVStack";
import { eColor } from '../../../lib/globalStyles';


export function TermsOfUseModalItem() {
  return (
    <MVStack stretchH stretchW style={{ 'alignItems': 'center' }}>
      <MText style={{ fontWeight: '700', marginBottom: 10 }} >Sodium Terms of Use</MText>
      <MText style={{ color: eColor.GrayContentText }} >Version 1.1</MText>
      <MText style={{ color: eColor.GrayContentText }}>Effective as of Jun 30, 2022</MText>
      <MDivider style={{ marginVertical: 10 }} />
      <MText numberOfLines={null}>
        Please review these Terms of Use (“Sequence User Terms”) carefully, as they set forth the legally binding terms and conditions that govern your use of our website located at https://sequence.xyz (“Website”) and the Sequence wallet (the “Wallet”), including related trademarks, software code, and other intellectual property (together, the “Sequence Services”).

        By accessing or using the Sequence Services, you agree to these Sequence User Terms on behalf of yourself and any entity you represent, and you represent and warrant that you have the right and authority to do so. You further represent and warrant that you are fully able and competent to enter into, and abide by and comply with, the Sequence User Terms.

        By accessing or using the Sequence Services, you represent that you are of the legal age of majority in your jurisdiction as may be required to access and use the Sequence Services. If you have not reached the age of majority in your jurisdiction but are at least thirteen (13) years of age, your legal guardian must review these Sequence User Terms and explain them to you before you use the Sequence Services.

        The Website and Wallet are both copyrighted works belonging to Horizon Blockchain Games Inc. (“Horizon,” “Company,” “us,” “our,” and “we”). Your submission of information, including personal information, through or in connection with the Sequence Services is governed by the terms of the Horizon Blockchain Games Inc. Privacy Policy as updated from time to time, available at https://sequence.xyz/privacy (“Privacy Policy”).   In order to access or use the Sequence Services you will be required to first accept the Privacy Policy.  You will be prompted to accept the Privacy Policy upon your initial registration of an Account by clicking to accept. You will be prompted to accept updates to the Privacy Policy from time to time when you log in to your Account by clicking to accept the updated Privacy Policy.

        When you accept the Privacy Policy, and any updates thereto, you consent to us collecting, accessing, using, processing, and retaining any personal information you provide to us so we may provide the Sequence Services to you. This consent does not affect any rights or obligations we or you have in accordance with data protection laws, privacy laws, and regulations.

        Some jurisdictions (which may include Quebec, Canada) do not allow mandatory arbitration, prohibitions against class actions or governing law and forums other than where the individual consumer is located. If you are located in one of these jurisdictions, the following sentence may not apply to you and you may have additional rights. These terms require the use of arbitration, as set forth in more detail in Section 8 below, on an individual basis to resolve disputes, rather than jury trials or class actions, and also limit the remedies available to you in the event of a dispute.

        1. Wallet

        1.1 Wallet Creation.

        The Wallet is a web-based smart wallet that runs on mobile and desktop platforms and provides users with access to an interface allowing them to execute instructions directly on a variety of Ethereum-compatible blockchain networks (“Supported Blockchain Networks”). The Wallet also allows users to view balances for digital assets that are compatible with the Wallet (“Blockchain Assets”), initiate transfers and transactions involving Blockchain Assets, and as an authenticating account to access Skyweaver and potentially other products and games. The Wallet also allows users to access decentralized applications, including, without limitation, decentralized exchanges (collectively "Dapp(s)") and engage in certain transactions, including swapping one Blockchain Assets for another Blockchain Asset on a peer-to-peer basis via such third-party Dapps (a "Swap") and bridging Blockchain Assets from one Supported Blockchain Network to another (a “Bridge”).

        In order to create an Account and open a Wallet, users must provide an email address or a user ID for either a Google, Facebook, Reddit, Discord or Twitch account (collectively “Login Credentials”) to be associated with the Wallet. If a user has not reached the age of majority in their jurisdiction but is at least thirteen (13) years of age, the user’s parent or legal guardian must sign up for a Wallet on behalf of the user by providing an email address to be associated with the account and agreeing to the Sequence User Terms.

        When you use the Sequence Services, you may also be using the services of one or more third-parties. Your use of third-party services ("Third-Party Services") will be subject to the privacy policies, terms of use and similar policies and terms, and fees of those third-party services.

        1.2 Wallet Access.

        Your Wallet is web-based software that is accessible locally on your device. Part of that software is a “private key” system used to secure your Wallet.  There are three private keys associated with your Wallet, and two private keys are required to access your Wallet at any given time.  One private key is stored locally on your device. Another private key is generated using the Login Credentials you provided to open your Account (“Account”). The third private key is maintained by Horizon.  When you log in to your Account/Wallet with your Login Credentials, you access the account using the private key stored on your device and the private key generated in connection with your Login Credentials.

        If you lose your device, you may still access your account using your Login Credentials and the private key maintained by Horizon.  If you cannot remember your Login Credentials, you may still access your account using your device and the private key maintained by Horizon.

        The Wallet allows you to access and transfer your Blockchain Assets. You control the Blockchain Assets accessible through the Wallet at any time. Your ability to access and transfer Blockchain Assets you own exists independently of the Wallet and you may choose to transfer your Blockchain Assets to a different wallet at any time. With respect to the Blockchain Assets accessible through your Wallet, Horizon does not have custody of such assets, and does not have the ability to transfer such assets. Only you have the ability to transfer your Blockchain Assets or initiate other transactions recorded on the blockchain. As such, you acknowledge and assume the risks below regarding the use of the Wallet:

        (a) A Wallet may be subject to certain exploits and Horizon is not responsible for any such exploits. While Horizon has taken a number of precautions to ensure the security of the Wallet, the technology is relatively new and it is not possible to guarantee that the code is 100% free from bugs or errors. Users accept all risks that arise from using the Wallet, including, and not limited to, the risk of any funds being lost due to an exploit.

        (b) You are solely responsible for securing your Login Credentials and any device you use to access your Wallet. You understand that anyone who obtains your Login Credentials and access to your device may access your Wallet with or without your authorization and may transfer any Blockchain Assets accessible through your Wallet.

        (c) The value of any Blockchain Asset, where value is attached to such an asset, may fluctuate. Horizon makes no guarantees as to the price or value of any Blockchain Asset accessible via a Wallet. You acknowledge and accept the risk that your Blockchain Assets, or any Blockchain Assets you may acquire, including by using the Wallet to access and interact with a third-party Dapp, may lose some or all of their value and you may suffer loss due to the fluctuation of prices and/or significant price slippage and cost.

        (d) The following risks are associated with using Blockchain Assets: the risk of losing private keys, theft resulting from third-parties discovering your private key, value fluctuation on the secondary market, disruptions to the relevant blockchain caused by network congestion, lack of usability of the assets due to a hard fork or other disruption to the relevant blockchain, or errors or vulnerabilities in the smart contract code associated with a given Blockchain Asset or transactions involving Blockchain Assets, including with respect to Swap or Bridge transactions. Transfers on the Ethereum and other blockchains are generally irreversible. Once an instruction, signed by the required private key(s), to transfer a Blockchain Asset from one blockchain address to another has been executed, such a transaction cannot be undone.

        (e) You are solely responsible for determining the tax implications and tax reporting requirements associated with transactions you engage in involving Blockchain Assets accessible through your Wallet, and for paying any applicable taxes. Horizon is not responsible for determining whether there are tax implications in connection with transactions involving Blockchain Assets accessible through Wallets, for reporting any such transactions, or for paying any applicable taxes.

        (f) Horizon may modify or discontinue support for the Wallet at any time. Horizon reserves the right, at any time and without notice, in our sole and absolute discretion, to modify the Wallet.

        (g) In the event of a change to an underlying blockchain network, or other network disruption, resulting in a fork of the existing blockchain into one (or more) additional blockchains, the Wallet may not support activity related to any new Blockchain Assets created as a result of the fork. In addition, in the event of a fork, transactions on the network may be disrupted.

        1.3 Fees.

        You may be charged fees in connection with some of the Sequence Services available to you, including fees related to Swaps or Bridges that you execute accessing third-party Dapps. We reserve the right to change those fees at any time, in our sole and absolute discretion. We will disclose the amount of fees we will charge you for the applicable Sequence Service at the time that you access the Sequence Service.

        You may incur charges from third-parties for use of Third-Party Services. For example, you may be charged fees via the Dapps that you may access via the Wallet. Third-party fees are not charged by Horizon and are not paid to Horizon. Under no circumstances shall Horizon incur any liability, of any kind, to you arising from or relating to fees charged to you by Third-Party Services linked to or accessed through the Sequence Services.

        Although we will attempt to provide accurate fee information, any such information reflects our estimate of fees, which may vary from the fees actually paid to use the Sequence Services and interact with the relevant blockchain. Digital asset pricing information may be higher or lower than prices available on platforms providing similar services.

        In connection with each Swap, you understand and agree that swap rates and digital asset prices displayed are estimates only that are provided using third-party data feeds, and that they may change at any time. Accordingly, the swap rates or digital asset prices displayed via the Sequence Services, including on the Swap interface, are estimates only and may be inaccurate. Horizon is not liable for, and you hereby forever release Horizon from, any losses or claims arising out of inaccurate estimates of swap rates or digital asset prices displayed via the Sequence Services.

        Each Supported Blockchain Network charges a fee for engaging in a transaction on the network. Those network transaction fees fluctuate over time depending on a variety of factors. You are solely responsible for paying network transaction fees associated with transactions you engage in on each blockchain network using the Wallet.  You are also solely responsible for any other third-party fees that may be incurred in connection with your use of the Wallet.

        1.4 Third-Party Services.

        The Sequence Services may contain links or otherwise provide access to Third-Party Services (including, without limitation, Dapps), and such Third-Party Services may enable certain features, such as Swaps and Bridges. When using a Dapp or other Third-Party Services, you understand that you are at no time transferring your assets to us. Sequence provides access to Third-Party Services as a convenience. Horizon does not have control over the content provided by Third-Party Services, does not warrant or endorse any Third-Party Service, and is not responsible for the availability or legitimacy of, the content, products or services on or accessible from those Third-Party Services (including any related website, resources or links displayed therein). We make no warranties or representations, express or implied, about such linked Third-Party Services, the third-parties they are owned and operated by, the information contained on them or the suitability of their products or services. You acknowledge sole responsibility for and assume all risk arising from your use of any third-party website, applications, or resources.

        1.5 Other Disclaimers.

        Horizon does not operate a Blockchain Asset exchange platform or offer trade execution or clearing services and, therefore, has no oversight, involvement, or control concerning your transactions using the Sequence Services. All transactions between users of Sequence Services are executed peer-to-peer directly between the users' Ethereum (or other network) addresses through third-party smart contracts. You are responsible for complying with all laws that may be applicable to or govern your use of the Sequence Services.

        You understand that Horizon is not registered or licensed by the Ontario Securities Commission, Commodity Futures Trading Commission ("CFTC"), Securities and Exchange Commission ("SEC"), or any financial regulatory authority in Canada, the United States or any other jurisdiction. No financial regulatory authority has reviewed or approved the use of the Sequence Services. The Sequence Services do not constitute advice or a recommendation concerning any commodity, security, or other Blockchain Asset or instrument. Horizon is not acting as an investment adviser or commodity trading adviser to any person or entity. Horizon does not make any representations or warranties as to the functionality of any Supported Blockchain Network, or that any Supported Blockchain Network will operate free from interruptions, delays, defects and/or errors that may delay, hinder or prevent the transmission of transactions or messages to or on such Supported Blockchain Network. The Sequence Services rely on emerging technologies, such as the Ethereum network.

        2. Representations.

        You make the following representations regarding your use of the Wallet:

        (a) You represent and warrant that you are legally permitted to use the Sequence Services in your jurisdiction including owning Blockchain Assets and interacting with the Sequence Services in any way. You further represent you are responsible for ensuring compliance with the laws of your jurisdiction and acknowledge that Horizon is not liable for your compliance or non-compliance with such laws.

        (b) You represent and warrant that you are not a person or entity identified on: (i) a list established under section 83.05 of the Criminal Code (Canada), any Regulations made under the United Nations Act (Canada), the Freezing Assets of Corrupt Foreign Officials Act (Canada), the Justice for Victims of Corrupt Foreign Officials Act (Canada), the Special Economic Measures Act (Canada) or any other Canadian statutes or regulations that take legislative measures against terrorist financing and against financial dealings with certain sanctioned individuals and entities; (ii) a list of specially designated national and/or blocked persons maintained by the Office of Foreign Assets Control of the United States Treasury Department; (iii) a list of denied persons or parties of concern maintained by the Bureau of Industry and Security of the United States Department of Commerce; or (iv) any similar list promulgated by an official agency, ministry or department of the United States.

        (c) You represent and warrant that you are not a resident of, or located in, any of the countries listed here [https://support.sequence.xyz/en/articles/6220364-sequence-list-of-restricted-regions] to which Canada or the United States has applied legal restrictions.

        (d) You represent that you will not (or attempt to) purchase, sell, rent, or give away access to your Wallet, create a Wallet using a false identity or information, or on behalf of someone other than yourself.

        (e) You represent that you will not disrupt, interfere with, or otherwise adversely affect the normal flow of the Wallet or otherwise act in a manner that may negatively affect other users' experience when using the Wallet. This includes taking advantage of errors and any other act that intentionally abuses or goes against the design of the Wallet.

        (f) We welcome feedback, comments, ideas, and suggestions for improvements to the Sequence Services ("Feedback"). You grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicensable and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon or improvements with respect to and otherwise exploit and commercialize the Feedback and any such derivative works and improvements in any manner and for any purpose.

        Horizon reserves the right to determine what conduct it considers to be a breach of these representations. Horizon reserves the right to take action as a result, which may include prohibiting you from accessing services provided by Horizon, in whole or in part. Any restrictions imposed by Horizon will not affect your ability to transfer your Blockchain Assets.

        3. Website Terms

        3.1 Access to the Website.

        (a) License.  Subject to these Sequence User Terms, Horizon grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Websites for your own personal and non-commercial use.

        (b) Certain Restrictions. The rights granted to you in these Sequence User Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Websites, whether in whole or in part, or any content displayed on the Websites; (b) you shall not (directly or indirectly) modify, decipher, disassemble, reverse compile or reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Sequence Services; (c) you shall not access the Websites in order to build a similar or competitive website, product, or service; (d) you shall not translate, or otherwise create derivative works, adaptations, translations or compilations of any part of the Sequence Services; (e) you shall not rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder; (f) you shall not frame or mirror any part of the Websites without Horizon’s express prior written consent; (g) you shall not create a database by systematically downloading and storing content related to the Sequence Services; (h) you shall not use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, harvest, index, “scrape,” “data mine” or in any way gather content related to the Sequence Services or reproduce or circumvent the navigational structure or presentation of the Sequence Services without Horizon’s express prior written consent; and (i) except as expressly stated herein, no part of the Websites may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means.  Unless otherwise indicated, any future release, update, or other addition to functionality of the Websites shall be subject to these Sequence User Terms.  All copyright and other proprietary notices on the Websites (or on any content displayed on the Websites) must be retained on all copies thereof.

        (c) Modification of the Websites. Horizon reserves the right, at any time, to modify, suspend, or discontinue the Websites (in whole or in part) with or without notice to you.  You agree that Horizon will not be liable to you or to any third-party for any modification, suspension, or discontinuation of the Websites or any part thereof.

        (d) No Support or Maintenance. You acknowledge and agree that Horizon will have no obligation to provide you with any support or maintenance in connection with the Websites, unless specifically contracted for under a separate agreement.

        (e) Ownership. Excluding any User Content that you may provide, you acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Websites and their content are owned by Horizon.  Neither these Sequence User Terms nor your access to the Websites transfers to you or any third-party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in these Sequence User Terms. Horizon reserves all rights not granted in these Sequence User Terms. There are no implied licenses granted under these Sequence User Terms.

        3.2 Accuracy of Information. We attempt to ensure that the information that we provide on the Websites is complete, accurate and current. Despite our efforts, the information on Websites may occasionally be inaccurate, incomplete or out of date. We make no representation as to the completeness, accuracy or correctness of any information on any Website.

        4. Disclaimers

        SOME JURISDICTIONS (WHICH MAY INCLUDE QUEBEC) DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY, INCLUDING LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE FOLLOWING LIMITATION MAY NOT APPLY TO YOU AND YOU MAY HAVE ADDITIONAL RIGHTS.

        THE SERVICES ARE PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS, AND HORIZON (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY, MERCHANTABLE QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT.  WE MAKE NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE.  IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SERVICES, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE.

        HORIZON DOES NOT ENDORSE ANY OTHER THIRD-PARTY AND SHALL NOT BE RESPONSIBLE IN ANY WAY FOR ANY TRANSACTIONS YOU ENTER INTO WITH OTHER USERS. YOU AGREE THAT HORIZON WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGES OF ANY SORT INCURRED AS THE RESULT OF ANY INTERACTIONS BETWEEN YOU AND OTHER USERS.

        5. Term and Termination

        These Sequence User Terms will remain in full force and effect while you use the Sequence Services.  We may suspend or terminate your rights to use the Sequence Services at any time for any reason at our sole discretion, including for any use of the Sequence Services in violation of these Sequence User Terms. Upon termination of your rights under these Sequence User Terms, your right to access and use the Sequence Services will terminate immediately. You understand that any termination of your rights may involve removal of your User Content from our live databases. Horizon will not have any liability whatsoever to you for any termination of your rights under these Sequence User Terms, including for deleting your account or blacklisting any network address you provide to us. Even after your rights under these Sequence User Terms are terminated, the following provisions of these Sequence User Terms will remain in effect: Section 4, Section 6, Section 7, Section 8, and Section 11.

        6. Indemnification

        You agree to indemnify and hold Horizon (and its officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third-party due to or arising out of: (i) your use of the Sequence Services; (ii) your violation of these Sequence User Terms; (iii) your violation of applicable laws or regulations; (iv) your User Content; or (v) Third-Party Services. Horizon reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.  You agree not to settle any matter without the prior written consent of Horizon. Horizon will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.

        7. Limitation on Liability

        SOME JURISDICTIONS (WHICH MAY INCLUDE QUEBEC, CANADA) DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY, INCLUDING LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE FOLLOWING LIMITATION MAY NOT APPLY TO YOU AND YOU MAY HAVE ADDITIONAL RIGHTS.

        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL HORIZON BE LIABLE TO YOU OR ANY THIRD-PARTY FOR ANY LOST PROFITS, LOST DATA, OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING OUT OF YOUR USE OF THE SEQUENCE SERVICES, EVEN IF HORIZON HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  ACCESS TO, AND USE OF, THE SERVICES IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR COMPUTER SYSTEM, OR LOSS OF DATA RESULTING THEREFROM. HORIZON SHALL NOT BE LIABLE UNDER ANY CIRCUMSTANCES FOR DAMAGES ARISING OUT OF OR IN ANY WAY RELATED TO SOFTWARE, PRODUCTS, SERVICES, AND/OR INFORMATION OFFERED OR PROVIDED BY THIRD-PARTIES AND ACCESSED THROUGH THE SEQUENCE SERVICES.

        HORIZON SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE ARISING OUT OF YOUR FAILURE TO KEEP YOUR PRIVATE KEYS OR LOGIN CREDENTIALS TO YOUR WALLET SECURE OR ANY OTHER UNAUTHORIZED ACCESS TO OR TRANSACTIONS INVOLVING YOUR WALLET.

        TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO A MAXIMUM OF FIFTY US DOLLARS (U.S. $50). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT.

        8. Dispute Resolution

        Please read this section carefully.  It is part of your contract with Horizon and affects your rights. You and Horizon are each considered “Parties” for the purpose of this section. SOME JURISDICTIONS (WHICH MAY INCLUDE QUEBEC, CANADA) DO NOT ALLOW MANDATORY ARBITRATION, PROHIBITIONS AGAINST CLASS ACTIONS OR GOVERNING LAW AND FORUMS OTHER THAN WHERE THE CONSUMER IS LOCATED.  IF YOU ARE LOCATED IN ONE OF THESE JURISDICTIONS, THE FOLLOWING MAY NOT APPLY TO YOU AND YOU MAY HAVE ADDITIONAL RIGHTS.

        8.1 Mediation. If any dispute occurs between the Parties relating to the application, interpretation, implementation or validity of these Sequence User Terms, the Parties agree to seek to resolve the dispute or controversy through mediation with Canadian Arbitration Association before pursuing any other proceedings. Nothing herein shall preclude any Party from seeking injunctive relief in the event that the Party perceives that without such injunctive relief, serious harm may be done to the Party. Any Party to the dispute may serve notice on the others of its desire to resolve a particular dispute by mediation. The mediator shall be appointed by agreement between the Parties or, if the Parties cannot agree within five days after receipt of the notice of intention to mediate, the mediator will be appointed by Canadian Arbitration Association. The mediation will be held at Toronto, Ontario, Canada. The Parties agree to attempt to resolve their dispute at mediation. The costs of the mediator shall be shared equally by the Parties. If the dispute has not been resolved within thirty days of the notice of desire to mediate, any Party may terminate the mediation and proceed to arbitration as set out below.

        8.2 Arbitration. Subject to the mediation provisions set out above, if any dispute or controversy occurs between the Parties relating to the interpretation or implementation of any of the provisions of this Agreement, the dispute will be resolved by arbitration at Canadian Arbitration Association pursuant to the general Canadian Arbitration Association Rules for Arbitration. Any Party may serve notice of its desire to refer a dispute to arbitration. The arbitration shall be conducted by a single arbitrator. The arbitration shall be held in Toronto, Ontario, Canada. The arbitration shall proceed in accordance with the provisions of the Arbitration Act (Ontario). The decision arrived at by the arbitrator shall be final and binding and no appeal shall lie therefrom. Judgement upon the award rendered by the arbitrator may be entered in any court having jurisdiction. The costs of the arbitrator shall be divided equally between the Parties.

        9. Disclosures.

        Horizon is located in Ontario, Canada. If you are a California resident, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Product of the California Department of Consumer Affairs by contacting them in writing at 400 R Street, Sacramento, CA 95814, or by telephone at (800) 952-5210.

        10. Electronic Communications.

        The communications between you and Horizon use electronic means, whether you use the Sequence Services or send us emails, or whether Horizon posts notices on the Sequence Services or communicates with you via email. For contractual purposes, you: (i) consent to receive communications from Horizon in an electronic form; and (ii) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Horizon provides to you electronically satisfy any legal requirement as if they were provided in a hardcopy writing. The foregoing does not affect your non-waivable rights.

        11. Governing Law and Jurisdiction

        SOME JURISDICTIONS HAVE CONSUMER PROTECTION AND OTHER LEGISLATION WHICH MAY APPLY TO THE SERVICES AND WHICH DO NOT ALLOW CERTAIN PROVISIONS SUCH AS RESTRICTIONS ON GOVERNING LAW OR JURISDICTION, LIMITATIONS OF LIABILITY AND EXCLUSION OF CERTAIN WARRANTIES, AMONG OTHERS. TO THE EXTENT THAT A RESTRICTION ON GOVERNING LAW OR JURISDICTION, LIMITATION, EXCLUSION, RESTRICTION OR OTHER PROVISION SET OUT BELOW IS SPECIFICALLY PROHIBITED BY APPLICABLE LAW, SUCH LIMITATION, EXCLUSION, RESTRICTION OR PROVISION MAY NOT APPLY TO YOU.

        These Sequence User Terms and any dispute or claim arising out of or in connection with their subject matter or formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with the law of Ontario. You agree that the courts of Ontario shall have exclusive jurisdiction to settle any dispute or claim arising out of or in connection with the subject matter or formation (including non-contractual disputes or claims) of these Sequence User Terms.

        If you are located outside of the United States or Canada, you use or access the Sequence Services solely at your own risk. The Sequence Services may not be appropriate or available for use in some jurisdictions. Horizon and its partners do not represent or warrant that the Sequence Services or any part thereof is appropriate or available for use in any particular jurisdiction other than the United States or Canada. In choosing to access the Sequence Services, you do so on your own initiative and at your own risk, and you are responsible for complying with all local laws, rules and regulations.

        12. General

        12.1 Entire Terms. These Sequence User Terms constitute the entire agreement between you and us regarding the use of the Sequence Services. The section titles in these Sequence User Terms are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation.” If any provision of these Sequence User Terms is, for any reason, held to be invalid or unenforceable, the other provisions of these Sequence User Terms will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. You confirm that you are acting on your own behalf and not for the benefit of any other person. Your relationship to Horizon is that of an independent contractor, and neither party is an agent or partner of the other.  These Sequence User Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Horizon’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.  Horizon may freely assign these Sequence User Terms.  The terms and conditions set forth in these Sequence User Terms shall be binding upon assignees.

        12.2 Changes. Unless otherwise required by applicable laws, which may include the laws of Quebec, Canada, if applicable (in which case, we will make changes in accordance with such laws), these Sequence User Terms are subject to occasional revision. If we make any substantial changes, you will be prompted to review those changes and click to accept the updated Sequence User Terms when you next log in to your Account.  These changes will be effective upon your acceptance of the updated Sequence User Terms.  In addition, continued use of our Sequence Services following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.

        12.3 Waiver. A waiver by Horizon of any right or remedy under these Sequence User Terms shall only be effective if it is in writing, executed by a duly authorized representative of Horizon and shall apply only to the circumstances for which it is given.  Our failure to exercise or enforce any right or remedy under these Sequence User Terms shall not operate as a waiver of such right or remedy, nor shall it prevent any future exercise or enforcement of such right or remedy.  No single or partial exercise of any right or remedy shall preclude or restrict the further exercise of any such right or remedy or other rights or remedies.

        12.4 Contact Information. You may contact us at any time regarding these Sequence User Terms at hello@horizon.io.
      </MText>
    </MVStack>
  )
}