import { MDivider } from "../../baseUI/mDivider";
import MText from "../../baseUI/mText";
import MVStack from "../../baseUI/mVStack";
import { eColor } from '../../../lib/globalStyles';


export function TermsOfUseModalItem() {
  return (
    <MVStack stretchH stretchW style={{ 'alignItems': 'center' }}>
      <MText style={{ fontWeight: '700', marginBottom: 10 }} >Terms of Use for Sodium Wallet</MText>
      {/* <MText style={{ color: eColor.GrayContentText }} >Version 1.1</MText> */}
      {/* <MText style={{ color: eColor.GrayContentText }}>Effective as of Jun 30, 2022</MText> */}
      <MDivider style={{ marginVertical: 0 }} />
      <MText numberOfLines={null}>
        {`
1.Introduction
This document stipulates the user terms ("User Terms") that oversee your utilization of the Sodium Wallet and the services provided by TICKER LOGIC CO., LTD., henceforth referred to as "TICKER LOGIC." The services include our websites (collectively, "Websites"), our Sodium Wallet (the "Wallet"), and any applications, content, products, and services made available by TICKER LOGIC (collectively with the Websites and the Wallet, the "Sodium Services"). Reading these User Terms thoroughly is important because they impact your legal rights and responsibilities.

2.Representations and Warranties
When using Sodium Services, you guarantee the following:
(a) You confirm your legal capacity and authority to accept these User Terms, to enter into a binding agreement with TICKER LOGIC, and to use the Sodium Services in compliance with these User Terms. You affirm that you are of legal age to form a binding contract (or if not, you've received your parent's or guardian's permission to use Sodium Services, and they've agreed to these User Terms on your behalf). You guarantee your compliance with all laws applicable to you or your use of the Sodium Services, including laws related to cryptocurrencies and their regulation.
(b) You guarantee that you are not a person or organization identified on: (i) a list established under section 83.05 of the Criminal Code (Canada), any Regulations made under the United Nations Act (Canada), the Freezing Assets of Corrupt Foreign Officials Act (Canada), the Justice for Victims of Corrupt Foreign Officials Act (Canada), the Special Economic Measures Act (Canada) or any other Canadian laws or regulations that enforce legislative measures against financing terrorism and financial dealings with particular sanctioned individuals and entities; (ii) a list of specifically designated nationals and/or blocked persons maintained by the Office of Foreign Assets Control of the United States Treasury Department; (iii) a list of denied individuals or parties of concern maintained by the Bureau of Industry and Security of the United States Department of Commerce; or (iv) any analogous list published by an official agency, ministry, or department of the United States.
(c) You assure that you are not a resident of, or situated in, any of the countries listed here https://sodiums.gitbook.io/sodium-documentation/terms/sodium-list-of-restricted-regions where Canada or the United States has imposed legal restrictions.
(d) You affirm that you will not (or attempt to) purchase, sell, rent, or give away access to your Sodium Wallet, create a Sodium Wallet using false information or identity, or on behalf of someone other than yourself.
(e) You assure that you will not disrupt, intrude with, or adversely influence the normal flow of the Sodium Wallet or behave in a way that may negatively impact other users' experiences when using the Sodium Wallet. This includes leveraging errors and any other act that intentionally abuses or contradicts the design of the Sodium Wallet.
(f) We appreciate your suggestions, ideas, comments, and potential improvements to the Sodium Services ("Feedback"). You grant us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, transferable license with the right to sublicense, under all intellectual property rights that you own or control, to use, copy, modify, create derivative works or improvements based on and commercialize the Feedback, and any such derivative works or improvements, in any manner and for any purpose.
TICKER LOGIC reserves the right to determine what conduct it considers to be a breach of these representations. TICKER LOGIC reserves the right to take action as a result, which may include prohibiting you from accessing services provided by TICKER LOGIC, in whole or in part. Any restrictions imposed by TICKER LOGIC will not affect your ability to transfer your Blockchain Assets.

3.Website Terms
3.1 Access to the Website.
(a) License. Subject to these User Terms, TICKER LOGIC grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Websites for your personal and non-commercial use.
(b) Certain Restrictions. The rights granted to you in these User Terms are subject to the following limitations: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or commercially exploit the Websites, either wholly or partially, or any content displayed on the Websites; (b) you shall not directly or indirectly modify, decipher, disassemble, reverse compile or reverse engineer, or attempt to derive any source code or underlying ideas or algorithms of any part of the Sodium Services; (c) you shall not access the Websites to build a similar or competitive website, product, or service; (d) you shall not translate, or create derivative works, adaptations, translations, or compilations of any part of the Sodium Services; (e) you shall not rent, lease, distribute, or transfer any of the rights that you receive hereunder; (f) you shall not frame or mirror any part of the Websites without TICKER LOGIC's express prior written consent; (g) you shall not create a database by systematically downloading and storing content related to the Sodium Services; (h) you shall not use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, harvest, index, “scrape,” “data mine,” or in any way gather content related to the Sodium Services or reproduce or circumvent the navigational structure or presentation of the Sodium Services without TICKER LOGIC's express prior written consent; and (i) except as expressly stated herein, no part of the Websites may be copied, reproduced, distributed, republished, downloaded, displayed, posted, or transmitted in any form or by any means. Unless otherwise indicated, any future release, update, or other addition to functionality of the Websites shall be subject to these User Terms. All copyright and other proprietary notices on the Websites (or on any content displayed on the Websites) must be retained on all copies thereof.
(c) Modification of the Websites. TICKER LOGIC reserves the right, at any time, to modify, suspend, or discontinue the Websites (in whole or in part) with or without notice to you. You agree that TICKER LOGIC will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Websites or any part thereof.
(d) No Support or Maintenance. You acknowledge and agree that TICKER LOGIC will have no obligation to provide you with any support or maintenance in connection with the Websites unless specifically contracted for under a separate agreement.
(e) Ownership. Excluding any User Content you may provide, you acknowledge that all the intellectual property rights in the websites and their content are owned by TICKER LOGIC, including copyrights, patents, trademarks, and trade secrets. Neither these User Terms nor your access to the Websites transfers to you or any third party any rights, title, or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in these User Terms. TICKER LOGIC reserves all rights not granted in these User Terms. There are no implied licenses granted under these User Terms.
3.2 Accuracy of Information. We strive to ensure that the information we provide on the Websites is complete, accurate, and current. Despite our efforts, the website information may occasionally be inaccurate, incomplete, or outdated. We do not represent the completeness, accuracy, or correctness of any information on any Website.

4.Disclaimers
SOME JURISDICTIONS (WHICH MAY INCLUDE QUEBEC) DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY, INCLUDING LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE FOLLOWING LIMITATION MAY NOT APPLY TO YOU AND YOU MAY HAVE ADDITIONAL RIGHTS.
THE SERVICES ARE PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS, AND TICKER LOGIC (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY, MERCHANTABLE QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WE MAKE NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE. IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SERVICES, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE.
TICKER LOGIC DOES NOT ENDORSE ANY OTHER THIRD PARTY AND SHALL NOT BE RESPONSIBLE IN ANY WAY FOR ANY TRANSACTIONS YOU ENTER INTO WITH OTHER USERS. YOU AGREE THAT TICKER LOGIC WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGES OF ANY SORT INCURRED AS THE RESULT OF ANY INTERACTIONS BETWEEN YOU AND OTHER USERS.

5.Term and Termination
These User Terms will remain in full force and effect while you use the Sodium Services. We may suspend or terminate your rights to use the Sodium Services at any time for any reason at our sole discretion, including for any use of the Sodium Services violating these User Terms. Upon termination of your rights under these User Terms, your right to access and use the Sodium Services will terminate immediately. You understand that any termination of your rights may involve the removal of your User Content from our live databases. TICKER LOGIC will not have any liability whatsoever to you for any termination of your rights under these User Terms, including for deleting your account or blacklisting any network address you provide to us. Even after your rights under these User Terms are terminated, the following provisions of these User Terms will remain in effect: Section 4, Section 6, Section 7, Section 8, and Section 11.

6.Indemnification
You agree to indemnify and hold TICKER LOGIC (and its officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of: (i) your use of the Sodium Services; (ii) your violation of these User Terms; (iii) your violation of applicable laws or regulations; (iv) your User Content; or (v) Third-Party Services. TICKER LOGIC reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of TICKER LOGIC. TICKER LOGIC will use reasonable efforts to notify you of any such claim, action, or proceeding upon becoming aware of it.

7.Third-Party Links & Ads; Other Users
7.1 Third-Party Links & Ads. The Sodium Services might contain links to third-party websites and services, and/or display advertisements for third parties (collectively, "Third-Party Links & Ads"). Such Third-Party Links & Ads are not under the control of TICKER LOGIC, and TICKER LOGIC is not responsible for any Third-Party Links & Ads. TICKER LOGIC provides access to these Third-Party Links & Ads only as a convenience to you. It does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links & Ads. You use all Third-Party Links & Ads at your own risk, and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links & Ads, the applicable third party’s terms and policies apply, including the third party’s privacy and data-gathering practices. You should make any investigation necessary or appropriate before proceeding with any transaction concerning Third-Party Links & Ads.
7.2 Other Users. Each Sodium Service user is solely responsible for any and all of its own User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others. We make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content. Your interactions with other Sodium Service users are solely between you and such users. You agree that TICKER LOGIC will not be responsible for any loss or damage incurred due to any such interactions. If there is a dispute between you and any Sodium Service user, we are not obligated to become involved.

8.Release
You hereby release and forever discharge TICKER LOGIC (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present, and future dispute, claim, controversy, demand, right, obligation, liability, action, and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Sodium Services (including any interactions with, or act or omission of, other Sodium Service users or any Third-Party Links & Ads).

9.Dispute Resolution
Please read this Arbitration Agreement carefully. It is part of your contract with TICKER LOGIC and affects your rights. It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.

10.Miscellaneous
10.1 Changes. These User Terms are subject to occasional revision. If we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any) and/or by prominently posting notice of the changes on our Sodium Services. Any changes to these User Terms will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on our Sodium Services. These changes will be effective immediately for new users of our Sodium Services. Continued use of our Sodium Services following notice of such changes shall indicate your acknowledgment of such changes and agreement to be bound by the terms and conditions of such changes.
10.2 Electronic Communications. The communications between you and TICKER LOGIC use electronic means, whether you use the Sodium Services or send us emails, or whether TICKER LOGIC posts notices on the Sodium Services or communicates with you via email. For contractual purposes, you (a) consent to receive communications from TICKER LOGIC in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that TICKER LOGIC provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. The foregoing does not affect your statutory rights.
10.3 Entire Terms. These User Terms constitute the entire agreement between you and us regarding the use of Sodium Services. Our failure to exercise or enforce any right or provision of these User Terms shall not operate as a waiver of such right or provision. The section titles in these User Terms are for convenience only and have no legal or contractual effect. The word "including" means "including without limitation." If any provision of these User Terms is held to be invalid or unenforceable, the other provisions of these User Terms will be unimpaired, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Your relationship to TICKER LOGIC is that of an independent contractor, and neither party is an agent or partner of the other. These User Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without TICKER LOGIC's prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.
10.4 Feedback. We welcome feedback, comments, and suggestions for improvements to the Sodium Services ("Feedback"). You can submit feedback by emailing us at support@sodiums.org. You grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicensable, and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon, and otherwise exploit the Feedback for any purpose.

11.Contact Information
If you have any questions about these User Terms or Sodium Services, please contact TICKER LOGIC at support@sodiums.org.
`}
      </MText>
    </MVStack>
  )
}